name: TestCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Create DI-file with Wire
        run: |
          go install github.com/google/wire/cmd/wire@latest
          ls
          cd ./balance 
          sudo wire

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...